name: Azure Static Web Apps CI/CD

on:
  workflow_call:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: lesli-spa
      - name: check folder
        run: ls -al && pwd
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_POND_0808EC90F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######